before_install:
  - "gem install bundler"
  - "rm ${BUNDLE_GEMFILE}.lock"
bundler_args: --without benchmark
language: ruby
services: memcached
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: rbx-19mode
notifications:
  email: false
