language: ruby
services: memcached

before_install:
  - gem install bundler
  - "rm ${BUNDLE_GEMFILE}.lock"
bundler_args: --without benchmark
before_script: bundle exec ruby -Ilib:test test/setup.rb
rvm:
  - 2.5
  - 3.0
notifications:
  email: false
