bundler_args: --without benchmark
language: ruby
services: memcached
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: 2.0.0
    - rvm: 2.1.0
    - rvm: rbx-19mode