language: ruby
services: memcached

before_install:
  - sudo apt-get remove --auto-remove -yqq libmemcached-dev
  - sudo apt-get -qq update
  - sudo apt-get install -yqq libmemcached-dev
  - gem install bundler
  - "rm ${BUNDLE_GEMFILE}.lock"
bundler_args: --without benchmark
before_script: bundle exec ruby -Ilib:test test/setup.rb
rvm:
  - 2.1
  - 2.2
  - 2.3.0
notifications:
  email: false
